name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  anchor_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm i typescript -g
      - uses: metadaobuilders/anchor-test@v1
      - run: cargo fmt -- --check && cargo clippy -- -Dwarnings
      - run: cargo test
